### ISSUE TITLE
Correct the principle username detection for OAuth 2.0 Client Credentials grant

### ISSUE THREAD

**Issue by boydingham** [ministryofjustice/prison-api#946]
### Expected Behavior

When the [_`/api/offenders/{offenderNo}`_](https://api-dev.prison.service.justice.gov.uk/swagger-ui/index.html#/offenders/newBookingUsingPOST) endpoint is called, an _`OFFENDER_BOOKINGS`_ record should be created in persistent storage.

### Current Behavior

The system fails to create the _`OFFENDER_BOOKINGS`_ record ([_full stack trace_](https://github.com/ministryofjustice/prison-api/files/6636191/prison.api.offenders.offenderno.bombs.0.a.log))...

```bash

...

org.springframework.dao.InvalidDataAccessApiUsageException: The given id must not be null!; nested exception is java.lang.IllegalArgumentException: The given id must not be null!

...

Caused by: java.lang.IllegalArgumentException: The given id must not be null!
        at org.springframework.util.Assert.notNull(Assert.java:201)
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findById(SimpleJpaRepository.java:297)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:529)
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:599)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java<===========--> 87% EXECUTING [5h 31m 35s]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:13
...
```

### Context

I am an ***external*** developer of a ***non-DPS*** system. My application [_is specified to consume API endpoints exposed by this project_](https://api-dev.prison.service.justice.gov.uk/swagger-ui/index.html#). My application will be authorized by [_HMPPS Auth_](https://github.com/ministryofjustice/hmpps-auth) using the OAuth 2.0 Client Credentials grant. 

While stepping through the debugger during investigation of a separate, unrelated issue, I had observed that Spring Security refers to the security principle as "_`AnonymousUser`_" during the OAuth 2.0 Client Credentials grant flow.

Assuming that an "_`AnonymousUser`_" would not have a user name, then the following two lines are reasonable suspects for the root cause of the reported "_`The given id must not be null`_" error...

1. [_`(username = ((UserDetails) userPrincipal).getUsername();)`_](https://github.com/ministryofjustice/prison-api/blob/main/src/main/java/uk/gov/justice/hmpps/prison/security/AuthenticationFacade.java#L34)
1. [_`staffUserAccountRepository.findById(currentUsername)`_](https://github.com/ministryofjustice/prison-api/blob/main/src/main/java/uk/gov/justice/hmpps/prison/service/PrisonerReleaseAndTransferService.java#L346)

### Steps to Reproduce 

1. Call the [_`/api/offenders/{offenderNo}`_](https://api-dev.prison.service.justice.gov.uk/swagger-ui/index.html#/offenders/newBookingUsingPOST) endpoint with a JWT access token issued by [_HMPPS Auth_](https://github.com/ministryofjustice/hmpps-auth) for an OAuth 2.0 Client Credentials grant.

### Your Environment

* Windows 10
* Docker Desktop Version 3.3.3 (64133)
* IntelliJ IDEA 2021.1.2 (Community Edition)
   - Build #IC-211.7442.40

**Comment by boydingham** [comment]
This one and these other two...

1. [_Fix o.s.d.DataIntegrityViolationException in /api/offenders/](https://github.com/ministryofjustice/prison-api/issues/943)
2. [_"Fix the build/config so that running locally on Windows 'Just Works'_](https://github.com/ministryofjustice/prisoner-offender-search/issues/155)

...Will be what I would like to pick your brains on @petergphillips @andymarke, whenever we get a chance to talk off line.

**Comment by petergphillips** [comment]
For endpoints that create data you need to provide an extra parameter when you create the client credentials of `username=<valid nomis user>`.

**Comment by boydingham** [comment]
Thank you @petergphillips,


> "_...For endpoints that create data you need to provide an extra parameter when you create the client credentials of `username=<valid nomis user>`..._"

I will give that a shot in a few.

I guess that's an example of what they call "_Implicit Knowledge_" (_aka, "Tribal Knowledge"_). Right? Because I haven't seen that documented anywhere. And I've read a ton of stuff so far about several different HMPPS/MOJ/DPS projects.

Please correct me if I'm wrong though. Please point me to the documentation of that, that I overlooked? TIA.

**Comment by boydingham** [comment]
> "..._`<valid nomis user>`_..."

I will proceed on the assumption that "_ITAG_USER_" is one such _`<valid nomis user>`_.

Or can you share any shortcuts to getting a hold of a known _`<valid nomis user>`_ @petergphillips ? It might be valuable to share that here; on the off chance that other future non-DPS devs stumble across this same issue. TIA.

**Comment by boydingham** [comment]
>> "..._`<valid nomis user>`_..."
>>    
>> _I will proceed on the assumption that "_ITAG_USER_" is one such `<valid nomis user>`_...


Dear "_other future non-DPS devs_",

I am pleased to report that "_ITAG_USER_" is, indeed, one such _`<valid nomis user>`_  :)

I confirmed that, @petergphillips, with two _`curl`_ calls from the command line...

1. Appending _`username=<valid nomis user>`_ to the token request to _`hmpps-auth`_
2. Calling the _`/api/offenders/{offenderId}/booking`_ endpoint with that access token
 
Now that leaves only the Spring Security OAuth 2.0 client credentials configuration so that it does those two things on my behalf, under the covers. Right @petergphillips? 

If you could share any shortcuts for (_or even better, links to documentation of_) that configuration, that'd be so super deluxe! TIA.

**Comment by boydingham** [comment]
>> ..._Now that leaves only the Spring Security OAuth 2.0 client credentials configuration so that it does those two things on my behalf, under the covers. Right @petergphillips?_...

The [_Customizing the Access Token Request_](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#customizing-the-access-token-request-3) section of the Spring Security OAuth 2.0 reference documentation offers some pretty decent guidance.

I'm reasonably certain as far as the "_What_" needs to be customized goes. My first stab at the specifics (_i.e., the "How"_) still needs a little more work though.

In the meantime, any links to hints, tips or suggestions are welcome @petergphillips. TIA.

**Comment by boydingham** [comment]
>> ...
>> _...My first stab at the specifics (i.e., the "How") still needs a little more work though..._

I've worked out a now-working configuration @petergphillips. I found the missing piece of the puzzle in [_the Spring Security JavaDoc_](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/client/web/method/annotation/OAuth2AuthorizedClientArgumentResolver.html#setClientCredentialsTokenResponseClient\(org.springframework.security.oauth2.client.endpoint.OAuth2AccessTokenResponseClient\))...

>> ...
>> _Use [OAuth2AuthorizedClientArgumentResolver(OAuth2AuthorizedClientManager)](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/client/web/method/annotation/OAuth2AuthorizedClientArgumentResolver.html#%3Cinit%3E(org.springframework.security.oauth2.client.OAuth2AuthorizedClientManager)) instead. Create an instance of [ClientCredentialsOAuth2AuthorizedClientProvider](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/client/ClientCredentialsOAuth2AuthorizedClientProvider.html) configured with a [DefaultClientCredentialsTokenResponseClient](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/client/ClientCredentialsOAuth2AuthorizedClientProvider.html#setAccessTokenResponseClient(org.springframework.security.oauth2.client.endpoint.OAuth2AccessTokenResponseClient)) (or a custom one) and than supply it to [DefaultOAuth2AuthorizedClientManager](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizedClientManager.html#setAuthorizedClientProvider(org.springframework.security.oauth2.client.OAuth2AuthorizedClientProvider))_
>> ...
>>   

The Spring Security OAuth 2.0 configuration I now have in place, now programmatically does the needful "_...provide an extra parameter when you create the client credentials of `username=<valid nomis user>`_" step.

Thanks again for sharing that _`username=<valid nomis user>`_ clue 👍

**Comment by petergphillips** [comment]
Sorry for the delay.  An example of where we configure the web client to add the `username` can be found in [WebClientConfiguration](https://github.com/ministryofjustice/whereabouts-api/blob/1c6e1172998cb247364f956899c58c3908b186c4/src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/WebClientConfiguration.kt#L150) and the code for the converter is [CustomOAuth2ClientCredentialsGrantRequestEntityConverter](https://github.com/ministryofjustice/whereabouts-api/blob/1c6e1172998cb247364f956899c58c3908b186c4/src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/CustomOAuth2ClientCredentialsGrantRequestEntityConverter.kt)
